export const SET_PHOTOS = "SET_PHOTOS";
export const SET_HEADER_PHOTO = "SET_HEADER_PHOTO";
export const SET_PAGE = "SET_PAGE";
export const SET_LOADING = "SET_LOADING";
export const SET_COLLECTIONS = "SET_COLLECTIONS";
export const SET_COLLECTION_PAGE = "SET_COLLECTION_PAGE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
